version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - './data:/data/db'

  mongoclient:
    image: mongoclient/mongoclient
    depends_on:
      - mongo
    ports:
      - 3300:3000
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: midnight
