version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - './data:/data/db'

  server:
    image: 'ghcr.io/samyosm/newsie:release'
    volumes:
      - './batches:/batches'
    ports:
      - "80:5000"
    expose:
      - '5000'
    restart: always
    environment:
      - FETCH_AUTHORIZATION=${FETCH_AUTHORIZATION}
      - BATCHES_DIR=/batches
    depends_on:
      - mongo
