version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - './data:/data/db'

  server:
    image: 'ghcr.io/samyosm/newsie:latest'
    volumes:
      - './config.json:/config.json'
    ports:
      - "80:5000"
    expose:
      - '5000'
    restart: always
    environment:
      - FETCH_AUTHORIZATION=${FETCH_AUTHORIZATION}
      - config=/config.json
    depends_on:
      - mongo
